name: Deploy CICD

on:
push:
branches: ["master"]


jobs:
deploy:
runs-on: ubuntu-latest
steps: 
 - uses: actions/checkout@v4
 - name: Deploy to Server
   uses: appleboy/ssh-action@master
   with: 
   host: ${{ secrets.HOST }}
   username: ${{secrets.USERNAME}}
   port: ${{secrets.PORT}} 
   key: ${{secrets.SSHKEY}}
   script: "cd /Desktop\HRMS_New_VER2024/package && ./.scripts/deploy.sh"
